#!/bin/bash
######
# Mate
######
#!/bin/sh
# unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
# exec /etc/X11/xinit/xinitrc

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey
vncconfig -iconic &
# x-terminal-emulator -geometry 80x24+10+10 -ls -title "VNC Desktop" &
mate-session &

#######
# xfce4
#######
# unset SESSION_MANAGER
# unset DBUS_SESSION_BUS_ADDRESS
# xrdb $HOME/.Xresources
# xfce4-session &
