# name: Build Docker Images

# on:
#     push:
#         branches: [main]
#     pull_request:
#         branches: [main]

# jobs:
#     build-slim:
#         name: "Build container"
#         runs-on: ubuntu-latest
#         steps:
#             - name: Set up Docker Buildx
#               uses: docker/setup-buildx-action@v1
#             - name: Login to DockerHub
#               uses: docker/login-action@v1
#               with:
#                   username: ${{ secrets.DOCKERHUB_USERNAME }}
#                   password: ${{ secrets.DOCKERHUB_TOKEN }}
#             - name: Login to GitHub Container Registry
#               uses: docker/login-action@v1
#               with:
#                   registry: ghcr.io
#                   username: ${{ github.repository_owner }}
#                   password: ${{ secrets.GITHUBCR_TOKEN }}
#             - name: Build and push
#               id: docker_build
#               uses: docker/build-push-action@v2
#               with:
#                   file: ./Dockerfile-Slim
#                   push: true
#                   tags: ilnerdchuck/hw-ci:slim,ghcr.io/ilnerdchuck/hw-ci:slim
#                   cache-from: type=registry,ref=ilnerdchuck/hw-ci:buildcache
#                   cache-to: type=registry,ref=ilnerdchuck/hw-ci:buildcache,mode=max
